/* ------------------------------------------------------------------ *
 *  MC Nexus — Integration Center (Phase 2 API preparation)
 *  Metadata + setup blueprint for every planned API connection.
 *  No live calls yet — this drives the Integration Center UI.
 * ------------------------------------------------------------------ */

export type IntegrationStatus = "connected" | "not_connected" | "error";
export type Health = "healthy" | "degraded" | "down" | "—";

export interface ChecklistItem { label: string; done: boolean; }

export interface Integration {
  key: string;
  name: string;
  emoji: string;
  accent: string;
  category: "Social" | "Advertising" | "Analytics" | "Workspace" | "Storage" | "AI" | "Email";
  status: IntegrationStatus;
  health: Health;
  lastSync: string;
  description: string;
  whyNeeded: string;
  dataProvided: string[];
  oauthFlow: string;
  oauthStatus: string;
  scopes: string[];
  permissions: string[];
  syncFrequency: string;
  rateLimit: string;
  webhook: string;
  envVars: string[];
  testingStatus: string;
  exampleResponse: string;
  limitations: string[];
  setupChecklist: ChecklistItem[];
  docsUrl: string;
}

const ck = (labels: string[], doneCount: number): ChecklistItem[] =>
  labels.map((label, i) => ({ label, done: i < doneCount }));

export const integrations: Integration[] = [
  {
    key: "meta-graph", name: "Meta Graph API", emoji: "🔷", accent: "#1877F2", category: "Social",
    status: "connected", health: "healthy", lastSync: "2 min ago",
    description: "Core Meta platform API powering Facebook & Instagram publishing, insights and messaging.",
    whyNeeded: "Publish and schedule posts, read page/account insights, and manage the unified inbox across Meta surfaces.",
    dataProvided: ["Page & IG account insights", "Post scheduling & publishing", "Comments & messages", "Audience demographics"],
    oauthFlow: "OAuth 2.0 authorization-code flow via Facebook Login. Long-lived page tokens exchanged server-side and refreshed before expiry.",
    oauthStatus: "Authorized · token valid 58 days",
    scopes: ["pages_show_list", "pages_read_engagement", "pages_manage_posts", "instagram_basic", "instagram_content_publish"],
    permissions: ["Manage Pages", "Publish content", "Read insights", "Read/respond to messages"],
    syncFrequency: "Insights every 15 min · webhooks realtime",
    rateLimit: "200 calls/hour/user · BUC weighted",
    webhook: "Subscribed · feed, mentions, messages",
    envVars: ["META_APP_ID", "META_APP_SECRET", "META_REDIRECT_URI", "META_WEBHOOK_VERIFY_TOKEN"],
    testingStatus: "Sandbox verified · live pending app review",
    exampleResponse: `{
  "data": [{ "id": "17895...", "reach": 11240, "impressions": 18320, "engagement": 902 }],
  "paging": { "cursors": { "after": "MjQ..." } }
}`,
    limitations: ["App review required for advanced permissions", "Business Use Case rate weighting", "24h messaging window"],
    setupChecklist: ck(["Create Meta app", "Configure Facebook Login", "Add redirect URI", "Request permissions", "Pass app review"], 4),
    docsUrl: "https://developers.facebook.com/docs/graph-api",
  },
  {
    key: "instagram-graph", name: "Instagram Graph API", emoji: "📷", accent: "#E1306C", category: "Social",
    status: "connected", health: "healthy", lastSync: "3 min ago",
    description: "Publish reels, carousels and stories, and read Instagram professional-account insights.",
    whyNeeded: "Schedule and auto-publish IG content and pull reach, engagement and follower analytics into the dashboard.",
    dataProvided: ["Media publishing (reel/carousel/image)", "Account & media insights", "Comments & mentions", "Hashtag search"],
    oauthFlow: "Uses Meta Login; IG professional account must be linked to a Facebook Page. Tokens shared with Meta Graph.",
    oauthStatus: "Authorized via Meta",
    scopes: ["instagram_basic", "instagram_content_publish", "instagram_manage_insights", "instagram_manage_comments"],
    permissions: ["Publish media", "Read insights", "Manage comments"],
    syncFrequency: "Insights every 15 min",
    rateLimit: "25 content publishes / 24h / account",
    webhook: "Subscribed · comments, mentions",
    envVars: ["META_APP_ID", "META_APP_SECRET", "IG_BUSINESS_ACCOUNT_ID"],
    testingStatus: "Sandbox verified",
    exampleResponse: `{ "id": "1789...", "media_type": "REELS", "permalink": "https://instagr.am/reel/...", "like_count": 842 }`,
    limitations: ["25 posts/day publishing cap", "No feed of other users", "Reels metrics delayed ~48h"],
    setupChecklist: ck(["Link IG to Page", "Convert to professional", "Grant IG permissions", "Test publish"], 4),
    docsUrl: "https://developers.facebook.com/docs/instagram-api",
  },
  {
    key: "facebook-graph", name: "Facebook Graph API", emoji: "📘", accent: "#1877F2", category: "Social",
    status: "connected", health: "healthy", lastSync: "3 min ago",
    description: "Manage Facebook Page posts, reach, engagement and audience insights.",
    whyNeeded: "Schedule Page content and surface reach/engagement and follower insights alongside other channels.",
    dataProvided: ["Page posts & scheduling", "Reach & engagement", "Audience insights", "Page messages"],
    oauthFlow: "OAuth 2.0 via Facebook Login with a long-lived page access token.",
    oauthStatus: "Authorized · token valid 58 days",
    scopes: ["pages_manage_posts", "pages_read_engagement", "read_page_mailboxes"],
    permissions: ["Publish Page content", "Read Page insights", "Read messages"],
    syncFrequency: "Insights every 15 min",
    rateLimit: "200 calls/hour/user",
    webhook: "Subscribed · feed",
    envVars: ["META_APP_ID", "META_APP_SECRET", "FB_PAGE_ID"],
    testingStatus: "Sandbox verified",
    exampleResponse: `{ "id": "1094..._5567...", "message": "…", "reach": 4821, "reactions": 214 }`,
    limitations: ["Organic reach limits", "Some insights 24–48h delayed"],
    setupChecklist: ck(["Select Page", "Grant permissions", "Generate page token", "Test publish"], 4),
    docsUrl: "https://developers.facebook.com/docs/pages-api",
  },
  {
    key: "google-ads", name: "Google Ads API", emoji: "🎯", accent: "#4285F4", category: "Advertising",
    status: "connected", health: "healthy", lastSync: "5 min ago",
    description: "Read and manage Google Ads campaigns, budgets, keywords and conversion performance.",
    whyNeeded: "Track spend, clicks, conversions and quality score, and surface budget pacing in the dashboard.",
    dataProvided: ["Campaign & ad-group metrics", "Keywords & negatives", "Budget pacing", "Conversions & CPA"],
    oauthFlow: "OAuth 2.0 with offline access; requires an approved developer token + linked MCC.",
    oauthStatus: "Authorized · refresh token stored",
    scopes: ["https://www.googleapis.com/auth/adwords"],
    permissions: ["Read campaign data", "Manage campaigns (optional)"],
    syncFrequency: "Every 30 min",
    rateLimit: "15,000 operations/day (basic access)",
    webhook: "N/A · polling via GAQL",
    envVars: ["GOOGLE_ADS_DEVELOPER_TOKEN", "GOOGLE_ADS_CLIENT_ID", "GOOGLE_ADS_CLIENT_SECRET", "GOOGLE_ADS_REFRESH_TOKEN", "GOOGLE_ADS_LOGIN_CUSTOMER_ID"],
    testingStatus: "Test account verified · basic access approved",
    exampleResponse: `{ "results": [{ "campaign": { "name": "Brand Search" }, "metrics": { "clicks": 612, "conversions": 41 } }] }`,
    limitations: ["Developer token approval required", "GAQL only", "Daily operation quota"],
    setupChecklist: ck(["Create Cloud project", "Apply for developer token", "Link MCC", "Generate refresh token", "Request basic access"], 5),
    docsUrl: "https://developers.google.com/google-ads/api/docs/start",
  },
  {
    key: "ga4", name: "Google Analytics 4 API", emoji: "📈", accent: "#E37400", category: "Analytics",
    status: "connected", health: "healthy", lastSync: "8 min ago",
    description: "GA4 Data API for sessions, users, engagement, conversions and revenue reporting.",
    whyNeeded: "Blend website analytics into the executive dashboard — traffic sources, top pages and conversions.",
    dataProvided: ["Users & sessions", "Engagement & retention", "Traffic sources", "Conversions & revenue", "Realtime"],
    oauthFlow: "Service account (server-to-server) with the GA4 property granting Viewer access.",
    oauthStatus: "Service account · Viewer granted",
    scopes: ["https://www.googleapis.com/auth/analytics.readonly"],
    permissions: ["Read GA4 property data"],
    syncFrequency: "Every 30 min · realtime on demand",
    rateLimit: "Core tokens: 250k/day/property",
    webhook: "N/A",
    envVars: ["GA4_PROPERTY_ID", "GOOGLE_APPLICATION_CREDENTIALS"],
    testingStatus: "Verified against live property",
    exampleResponse: `{ "rows": [{ "dimensionValues": [{ "value": "Instagram" }], "metricValues": [{ "value": "8421" }] }] }`,
    limitations: ["Data freshness up to ~4h for some dims", "Sampling on large ranges", "Cardinality limits"],
    setupChecklist: ck(["Create service account", "Add to GA4 property", "Enable Data API", "Store credentials"], 4),
    docsUrl: "https://developers.google.com/analytics/devguides/reporting/data/v1",
  },
  {
    key: "search-console", name: "Google Search Console API", emoji: "🧭", accent: "#458CF5", category: "Analytics",
    status: "connected", health: "degraded", lastSync: "1 h ago",
    description: "Search performance — clicks, impressions, CTR, average position and index coverage.",
    whyNeeded: "Monitor organic search health and top queries to guide SEO and content decisions.",
    dataProvided: ["Query & page performance", "Clicks / impressions / CTR", "Average position", "Index coverage"],
    oauthFlow: "OAuth 2.0 or service account with the verified Search Console property.",
    oauthStatus: "Authorized · re-auth recommended",
    scopes: ["https://www.googleapis.com/auth/webmasters.readonly"],
    permissions: ["Read search analytics", "Read index coverage"],
    syncFrequency: "Daily (data lags ~2–3 days)",
    rateLimit: "1,200 queries/min",
    webhook: "N/A",
    envVars: ["GSC_SITE_URL", "GOOGLE_APPLICATION_CREDENTIALS"],
    testingStatus: "Verified · token nearing expiry",
    exampleResponse: `{ "rows": [{ "keys": ["public speaking coach"], "clicks": 92, "impressions": 1840, "position": 6.2 }] }`,
    limitations: ["2–3 day data delay", "1000 rows/request", "16-month history cap"],
    setupChecklist: ck(["Verify property", "Grant API access", "Enable API", "Test query"], 3),
    docsUrl: "https://developers.google.com/webmaster-tools",
  },
  {
    key: "workspace", name: "Google Workspace Admin SDK", emoji: "🏢", accent: "#34A853", category: "Workspace",
    status: "connected", health: "healthy", lastSync: "20 min ago",
    description: "Directory & reports for Workspace users, aliases, storage and login activity.",
    whyNeeded: "Show workspace status — users, aliases, storage usage and recent logins — for ops oversight.",
    dataProvided: ["Users & aliases", "Storage usage", "Login activity", "Subscription info"],
    oauthFlow: "Service account with domain-wide delegation impersonating an admin.",
    oauthStatus: "Domain-wide delegation enabled",
    scopes: ["https://www.googleapis.com/auth/admin.directory.user.readonly", "https://www.googleapis.com/auth/admin.reports.usage.readonly"],
    permissions: ["Read directory", "Read usage reports"],
    syncFrequency: "Hourly",
    rateLimit: "2,400 queries/min",
    webhook: "N/A",
    envVars: ["WORKSPACE_ADMIN_EMAIL", "GOOGLE_APPLICATION_CREDENTIALS"],
    testingStatus: "Verified",
    exampleResponse: `{ "users": [{ "primaryEmail": "team@maincharacter.nl", "isAdmin": false }], "storageUsed": "78%" }`,
    limitations: ["Requires super-admin delegation", "Reports lag up to 48h"],
    setupChecklist: ck(["Create service account", "Enable domain-wide delegation", "Authorize scopes", "Test directory read"], 4),
    docsUrl: "https://developers.google.com/admin-sdk",
  },
  {
    key: "youtube", name: "YouTube Data API", emoji: "📺", accent: "#FF0000", category: "Social",
    status: "connected", health: "healthy", lastSync: "12 min ago",
    description: "Channel analytics, uploads and video performance for the YouTube channel.",
    whyNeeded: "Track subscribers, views and watch time, and manage uploads/thumbnails from one place.",
    dataProvided: ["Channel & video stats", "Views & watch time", "Subscribers", "Upload management"],
    oauthFlow: "OAuth 2.0 with offline access for the channel owner.",
    oauthStatus: "Authorized · refresh token stored",
    scopes: ["https://www.googleapis.com/auth/youtube.readonly", "https://www.googleapis.com/auth/youtube.upload"],
    permissions: ["Read analytics", "Upload videos", "Manage thumbnails"],
    syncFrequency: "Every 30 min",
    rateLimit: "10,000 quota units/day",
    webhook: "PubSubHubbub for new uploads",
    envVars: ["YOUTUBE_CLIENT_ID", "YOUTUBE_CLIENT_SECRET", "YOUTUBE_REFRESH_TOKEN"],
    testingStatus: "Verified",
    exampleResponse: `{ "items": [{ "statistics": { "subscriberCount": "6210", "viewCount": "88240" } }] }`,
    limitations: ["Quota units per operation", "Upload = 1600 units", "Analytics separate API"],
    setupChecklist: ck(["Create Cloud project", "Enable Data API", "Configure OAuth consent", "Generate refresh token"], 4),
    docsUrl: "https://developers.google.com/youtube/v3",
  },
  {
    key: "linkedin", name: "LinkedIn API", emoji: "💼", accent: "#0A66C2", category: "Social",
    status: "not_connected", health: "—", lastSync: "Never",
    description: "Company-page posting, share analytics and follower demographics.",
    whyNeeded: "Schedule thought-leadership posts and track impressions, CTR and follower growth.",
    dataProvided: ["Organization posts", "Share statistics", "Follower demographics", "Profile views"],
    oauthFlow: "OAuth 2.0 with member authorization; requires approved Marketing Developer Platform access.",
    oauthStatus: "Not authorized",
    scopes: ["r_organization_social", "w_organization_social", "rw_organization_admin"],
    permissions: ["Read org posts", "Publish org posts", "Read analytics"],
    syncFrequency: "Hourly (when connected)",
    rateLimit: "Throttled per app/member/day",
    webhook: "N/A",
    envVars: ["LINKEDIN_CLIENT_ID", "LINKEDIN_CLIENT_SECRET", "LINKEDIN_ORG_URN"],
    testingStatus: "Awaiting product access approval",
    exampleResponse: `{ "elements": [{ "totalShareStatistics": { "impressionCount": 22140, "clickCount": 611 } }] }`,
    limitations: ["Marketing Developer Platform approval", "Limited analytics granularity", "Strict throttling"],
    setupChecklist: ck(["Create LinkedIn app", "Request Marketing access", "Verify company page", "Authorize scopes"], 1),
    docsUrl: "https://learn.microsoft.com/linkedin/marketing",
  },
  {
    key: "tiktok", name: "TikTok Business API", emoji: "🎵", accent: "#000000", category: "Social",
    status: "not_connected", health: "—", lastSync: "Never",
    description: "Video insights, posting and follower analytics for the TikTok business account.",
    whyNeeded: "Surface views, engagement and follower growth, and schedule content to TikTok.",
    dataProvided: ["Video performance", "Follower analytics", "Content posting", "Trending sounds"],
    oauthFlow: "OAuth 2.0 via TikTok for Developers; app must be approved for Content Posting API.",
    oauthStatus: "Not authorized",
    scopes: ["user.info.basic", "video.list", "video.publish"],
    permissions: ["Read profile", "Read video insights", "Publish video"],
    syncFrequency: "Every 30 min (when connected)",
    rateLimit: "Per-app quota; publish caps apply",
    webhook: "Available for post status",
    envVars: ["TIKTOK_CLIENT_KEY", "TIKTOK_CLIENT_SECRET", "TIKTOK_REDIRECT_URI"],
    testingStatus: "Sandbox only · awaiting app approval",
    exampleResponse: `{ "data": { "videos": [{ "id": "72...", "view_count": 18240, "like_count": 1320 }] } }`,
    limitations: ["Content Posting API approval required", "Publish caps", "Sandbox before production"],
    setupChecklist: ck(["Create TikTok app", "Request Content Posting API", "Configure redirect", "Pass review"], 1),
    docsUrl: "https://developers.tiktok.com",
  },
  {
    key: "cloudinary", name: "Cloudinary", emoji: "🖼️", accent: "#3448C5", category: "Storage",
    status: "connected", health: "healthy", lastSync: "1 min ago",
    description: "Media storage, transformation and delivery for all creative assets.",
    whyNeeded: "Store, optimize and serve images/videos used across posts, previews and thumbnails.",
    dataProvided: ["Asset upload & storage", "On-the-fly transforms", "CDN delivery", "Usage metrics"],
    oauthFlow: "API key/secret (server-side signed uploads). No user OAuth.",
    oauthStatus: "API key · active",
    scopes: ["upload", "admin (usage)"],
    permissions: ["Upload assets", "Transform", "Read usage"],
    syncFrequency: "On upload · usage hourly",
    rateLimit: "Plan-based (uploads/transformations)",
    webhook: "Upload notification webhook",
    envVars: ["CLOUDINARY_CLOUD_NAME", "CLOUDINARY_API_KEY", "CLOUDINARY_API_SECRET"],
    testingStatus: "Verified",
    exampleResponse: `{ "public_id": "mc/reel_0721", "secure_url": "https://res.cloudinary.com/...", "bytes": 4210233 }`,
    limitations: ["Plan storage/bandwidth caps", "Transformation credits"],
    setupChecklist: ck(["Create account", "Copy API credentials", "Configure upload preset", "Test signed upload"], 4),
    docsUrl: "https://cloudinary.com/documentation",
  },
  {
    key: "google-drive", name: "Google Drive", emoji: "📁", accent: "#1FA463", category: "Storage",
    status: "connected", health: "healthy", lastSync: "18 min ago",
    description: "Cloud file storage for raw footage, deliverables and shared documents.",
    whyNeeded: "Pull raw assets and store deliverables the team already keeps in Drive.",
    dataProvided: ["File list & metadata", "Upload/download", "Folder structure", "Sharing"],
    oauthFlow: "OAuth 2.0 with offline access; drive.file scope for least privilege.",
    oauthStatus: "Authorized · refresh token stored",
    scopes: ["https://www.googleapis.com/auth/drive.file", "https://www.googleapis.com/auth/drive.readonly"],
    permissions: ["Read files", "Upload files", "Manage app-created files"],
    syncFrequency: "On demand · changes via push",
    rateLimit: "12,000 queries/min/project",
    webhook: "Drive push notifications (changes)",
    envVars: ["GDRIVE_CLIENT_ID", "GDRIVE_CLIENT_SECRET", "GDRIVE_REFRESH_TOKEN"],
    testingStatus: "Verified",
    exampleResponse: `{ "files": [{ "id": "1AbC...", "name": "podcast_raw_07.mp4", "mimeType": "video/mp4" }] }`,
    limitations: ["Per-user rate limits", "drive.file only sees app files"],
    setupChecklist: ck(["Enable Drive API", "Configure OAuth consent", "Generate refresh token", "Test list"], 4),
    docsUrl: "https://developers.google.com/drive/api",
  },
  {
    key: "dropbox", name: "Dropbox", emoji: "🗄️", accent: "#0061FF", category: "Storage",
    status: "not_connected", health: "—", lastSync: "Never",
    description: "Alternative cloud storage for large media handoffs with external collaborators.",
    whyNeeded: "Optional backup/handoff channel for partners who work in Dropbox.",
    dataProvided: ["File list & metadata", "Upload/download", "Shared links"],
    oauthFlow: "OAuth 2.0 with refresh tokens (offline). Scoped app access.",
    oauthStatus: "Not authorized",
    scopes: ["files.content.read", "files.content.write", "sharing.read"],
    permissions: ["Read files", "Write files", "Create shared links"],
    syncFrequency: "On demand (when connected)",
    rateLimit: "Per-app data transfer limits",
    webhook: "Dropbox webhooks (file changes)",
    envVars: ["DROPBOX_APP_KEY", "DROPBOX_APP_SECRET", "DROPBOX_REFRESH_TOKEN"],
    testingStatus: "Not started",
    exampleResponse: `{ "entries": [{ ".tag": "file", "name": "thumb_v3.png", "size": 184223 }] }`,
    limitations: ["Data transfer caps", "Scoped-app migration required"],
    setupChecklist: ck(["Create Dropbox app", "Set permissions", "Generate refresh token", "Test upload"], 0),
    docsUrl: "https://www.dropbox.com/developers/documentation",
  },
  {
    key: "openai", name: "OpenAI API", emoji: "🤖", accent: "#10A37F", category: "AI",
    status: "connected", health: "healthy", lastSync: "just now",
    description: "AI generation for caption drafting, translation and content ideation.",
    whyNeeded: "Power AI caption drafts, EN↔NL translation and the future AI assistant.",
    dataProvided: ["Text generation", "Translation", "Summarization", "Embeddings"],
    oauthFlow: "API key (server-side, secret). No user OAuth.",
    oauthStatus: "API key · active",
    scopes: ["chat.completions", "embeddings"],
    permissions: ["Generate text", "Create embeddings"],
    syncFrequency: "On demand",
    rateLimit: "Tier-based TPM/RPM",
    webhook: "N/A",
    envVars: ["OPENAI_API_KEY", "OPENAI_ORG_ID"],
    testingStatus: "Verified",
    exampleResponse: `{ "choices": [{ "message": { "role": "assistant", "content": "Here's a sharper hook…" } }] }`,
    limitations: ["Token & rate limits per tier", "Cost per token", "No PII in prompts"],
    setupChecklist: ck(["Create API key", "Set usage limits", "Store secret", "Test completion"], 4),
    docsUrl: "https://platform.openai.com/docs",
  },
  {
    key: "smtp", name: "SMTP (Email)", emoji: "✉️", accent: "#6B7280", category: "Email",
    status: "connected", health: "healthy", lastSync: "30 min ago",
    description: "Transactional email for approvals, reminders and notification digests.",
    whyNeeded: "Send approval requests, deadline reminders and digests to the team and clients.",
    dataProvided: ["Transactional send", "Delivery status", "Bounce/complaint events"],
    oauthFlow: "SMTP credentials or provider API key (SendGrid/Postmark/SES).",
    oauthStatus: "Credentials · active",
    scopes: ["mail.send"],
    permissions: ["Send email", "Read delivery events"],
    syncFrequency: "On event",
    rateLimit: "Provider send limits",
    webhook: "Delivery/bounce webhooks",
    envVars: ["SMTP_HOST", "SMTP_PORT", "SMTP_USER", "SMTP_PASSWORD", "MAIL_FROM"],
    testingStatus: "Verified · test email delivered",
    exampleResponse: `{ "messageId": "<a1b2@mc-nexus>", "accepted": ["onyema@maincharacter.nl"], "response": "250 OK" }`,
    limitations: ["Provider daily send caps", "SPF/DKIM/DMARC required for deliverability"],
    setupChecklist: ck(["Choose provider", "Verify sending domain", "Configure SPF/DKIM", "Send test"], 4),
    docsUrl: "https://nodemailer.com",
  },
];

export const integrationCategories = ["All", "Social", "Advertising", "Analytics", "Workspace", "Storage", "AI", "Email"] as const;
